# Informazioni sul sito
title: Twentyone
email: me@whiterabbit21m.org
description: >- # questo significa ignorare newline fino a "baseurl:"
  Questo è il mio sito personale creato con Jekyll. Qui condivido i miei pensieri
  su sviluppo web, design e tecnologia.
baseurl: "" # il sottopath del tuo sito, e.g. /blog
url: "https://www.whiterabbit21m.org" # l'host base & protocollo per il tuo sito, e.g. http://example.com

# Social media
twitter_username: whiterabbit21m
github_username:  whiterabbit21m
telegram_username: whiterabbit21m
facebook_username: tuousername
instagram_username: tuousername
linkedin_username: tuousername

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Esclusioni dalla conversione
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .gitignore

# Impostazioni Sass
sass:
  sass_dir: _sass
  style: compressed

# Impostazioni delle collezioni
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  products:
    output: true
    permalink: /products/:name

# Impostazioni di default per i post e i prodotti
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "whiterabbit21m"
      comments: true
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Impostazioni di paginazione
paginate: 6
paginate_path: "/blog/page:num/"

# Impostazioni SEO
twitter:
  username: whiterabbit21m
  card: summary_large_image
logo: /assets/images/logo.png
social:
  name: whiterabbit21m
  links:
    - https://twitter.com/whiterabbit21m
    - https://www.facebook.com/tuousername
    - https://www.linkedin.com/in/tuousername
    - https://github.com/whiterabbit21m
    - https://t.me/whiterabbit21m

# Analytics (decommentare e aggiungere il tuo ID quando pronto)
# google_analytics: UA-XXXXXXXX-X

# Commenti (esempio con Disqus, decommentare quando pronto)
# disqus:
#   shortname: your-disqus-shortname

# Altre impostazioni personalizzate
author: whiterabbit21m
timezone: Europe/Rome
lang: it

# Impostazioni per le immagini
img_path: /assets/images/

# Opzioni per il feed RSS
feed:
  path: feed.xml

# Impostazioni per la ricerca (se utilizzi un plugin di ricerca)
# search: true

# Impostazioni per la compressione HTML (se utilizzi un plugin di compressione)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]

# Impostazioni per i link permanenti
permalink: /:categories/:title/

# Impostazioni per i tag
tag_page_layout: tag_page
tag_page_dir: tag

# Configurazione del livereload (utile durante lo sviluppo)
livereload: true
