# Site/SEO settings
email: me@whiterabbit21m.org
baseurl: ""
paginate: 99 # TODO: Fix endless scroll / pagination
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: WhiteRabbit21m
title: www.whiterabbit21m.org
code: WR
description: >
  Thoughts about Bitcoin and other things.
url: https://www.whiterabbit21m.org
twitter_username: whiterabbit21m
default_img: /assets/images/avatar.jpg
social:
  - name: twitter
    url: https://twitter.com/whiterabbit21m
  - name: nostr
    url: nostr:npub130fu8uxy4mgzyn4pd09msfuj8rylrv5jz2jdpuxxwxv7g9sg0pcq00j4ve
  - name: telegram
    url: https://t.me/whiterabbit21m
  - name: github
    url: https://github.com/whiterabbit21m
  - name: bitcoin
    url: https://www.whiterabbit21m.org/support
  
# Collections
collections_dir: collections
collections:
  posts:
    title: Posts
  threads:
    title: Threads
    output: true
    permalink: /threads/:slug
  translations:
    title: Translations
    output: false
  books:
    title: Books
    output: true
    permalink: /books/:slug
  episodes:
    title: Episodes
    output: true

# Author settings
author:
  - name: WhiteRabbit21m
    bio: Writing words and code for Bitcoin.
    url: https://www.whiterabbit21m.org/contact

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
include: [".well-known"]
exclude:
  - env
  - scripts
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
